on right click on stone button:
    set {_shulker} to block south of event-block

    if {_shulker} is red shulker box:
        send "赤色のシェルカーを選択" to player
    else if {_shulker} is blue shulker box:
        send "青色のシェルカーを選択" to player
    else if {_shulker} is green shulker box:
        send "緑色のシェルカーを選択" to player
    else if {_shulker} is yellow shulker box:
        send "黄色のシェルカーを選択" to player
    else if {_shulker} is purple shulker box:
        send "紫色のシェルカーを選択" to player
