import minescript as m
import random

# プレイヤーリスト
players = ["crocadooo", "test1", "test2", "test3", "test4"]

# 進捗リスト（サンプルから抜粋）
advancements = [
    "You've Got a Friend in Me",
    "Who is Cutting Onions?",
    "With Our Powers Combined!",
    "Oh Shiny",
    "Country Lode, Take Me Home",
    "Good as New",
    "Suit Up",
    "Smithing with Style",
    "Very Very Frightening",
    "Hot Stuff",
    "Stay Hydrated!",
    "Minecraft: Trial(s) Edition",
    "Whatever Floats Your Goat!",
    "Free the End",
    "Surge Protector",
    "A Furious Cocktail",
    "Best Friends Forever",
    "Careful Restoration",
    "Glow and Behold!",
    "Bring Home the Beacon",
    "Not Today, Thank You",
    "When the Squad Hops into Town",
    "Isn't It Iron Pick",
    "The Whole Pack",
    "Local Brewery",
    "The Next Generation",
    "It Spreads",
    "Fishy Business",
    "Hot Tourist Destinations",
    "Caves & Cliffs",
    "Over-Overkill",
    "Shear Brilliance",
    "This Boat Has Legs",
    "Sniper Duel",
    "Great View From Up Here",
    "How Did We Get Here?",
    "Bullseye",
    "Spooky Scary Skeleton",
    "Two by Two",
    "Stone Age",
    "Two Birds, One Arrow",
    "We Need to Go Deeper",
    "Who's the Pillager Now?",
    "Getting an Upgrade",
    "Light as a Rabbit",
    "Tactical Fishing",
    "Respecting the Remnants",
    "Zombie Doctor",
    "Little Sniffs",
    "The City at the End of the Game",
    "Ice Bucket Challenge",
    "Remote Getaway",
    "Into Fire",
    "War Pigs",
    "Take Aim",
    "Total Beelocation",
    "Lighten Up",
    "Arbalistic",
    "Under Lock and Key",
    "The End... Again...",
    "Acquire Hardware",
    "Not Quite \"Nine\" Lives",
    "Revaulting",
    "Cover Me with Diamonds",
    "Sky's the Limit",
    "Bukkit Bukkit",
    "Wax Off",
    "Hired Help",
    "Sneak 100",
    "Return to Sender",
    "Sweet Dreams",
    "You Need a Mint",
    "Monsters Hunted",
    "Heart Transplanter",
    "Enchanter",
    "Smells Interesting",
    "Voluntary Exile",
    "Eye Spy",
    "Is It a Bird?",
    "Serious Dedication",
    "Postmortal",
    "Monster Hunter",
    "Adventuring Time",
    "Isn't It Scute?",
    "Planting the Past",
    "A Seedy Place",
    "Those Were the Days",
    "The Cutest Predator",
    "Birthday Song",
    "Is It a Plane?",
    "Feels Like Home",
    "Star Trader",
    "Wax On",
    "Sound of Music",
    "Hero of the Village",
    "Hidden in the Depths",
    "Beaconator",
    "Withering Heights",
    "A Balanced Diet",
    "Subspace Bubble",
    "The Power of Books",
    "Bee Our Guest",
    "What a Deal!",
    "Is It a Balloon?",
    "Crafting a New Look",
    "Uneasy Alliance",
    "Diamonds!",
    "The Healing Power of Friendship!",
    "A Terrible Fortress",
    "A Throwaway Joke",
    "Crafters Crafting Crafters",
    "Sticky Situation",
    "Ol' Betsy",
    "Cover Me in Debris",
    "The End?",
    "The Parrots and the Bats",
    "Blowback",
    "A Complete Catalogue",
    "Who Needs Rockets?"
]

# ランダムで30件生成
for _ in range(30):
    player = random.choice(players)
    advancement = random.choice(advancements)
    
    # "made the advancement" と "completed the challenge" と "reached the goal" をランダムで
    action_type = random.choices(
        ["has made the advancement", "has completed the challenge", "has reached the goal"],
        weights=[0.6, 0.3, 0.1], k=1
    )[0]
    
    m.execute(f'/tellraw @a "{player} {action_type} [{advancement}]"')
